# Generated by Django 5.2.5 on 2025-10-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DpGradeBoundaries',
            fields=[
                ('subject', models.TextField(db_column='subject', primary_key=True, serialize=False)),
                ('level', models.TextField(blank=True, null=True)),
                ('grade', models.TextField(blank=True, null=True)),
                ('min_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'dp_grade_boundaries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LmsUsersPasswordresetotp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('otp', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('used', models.TextField(blank=True, null=True)),
                ('user_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'LMS_users_passwordresetotp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LmsUsersStaffpreapproved',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField(blank=True, null=True)),
                ('role', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('department', models.TextField(blank=True, null=True)),
                ('invite_token', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('used', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'LMS_users_staffpreapproved',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LmsUsersUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.TextField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.TextField(blank=True, null=True)),
                ('username', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('is_staff', models.TextField(blank=True, null=True)),
                ('is_active', models.TextField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('role', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'LMS_users_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TokenBlacklistBlacklistedtoken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('blacklisted_at', models.DateTimeField(blank=True, null=True)),
                ('token_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'token_blacklist_blacklistedtoken',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TokenBlacklistOutstandingtoken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.TextField(blank=True, null=True)),
                ('jti', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'token_blacklist_outstandingtoken',
                'managed': False,
            },
        ),
    ]
