# Generated by Django 5.2.5 on 2026-02-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dpgradeboundaries_lmsuserspasswordresetotp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentsNonAcademic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_id', models.TextField(blank=True, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('grade', models.TextField(blank=True, null=True)),
                ('assessment_type', models.TextField(blank=True, null=True)),
                ('task_name', models.TextField(blank=True, null=True)),
                ('student_score', models.TextField(blank=True, null=True)),
                ('max_score_old', models.TextField(blank=True, null=True)),
                ('total_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descriptive_analysis', models.TextField(blank=True, null=True)),
                ('prescriptive_analysis', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assessments_non_academic',
                'managed': False,
            },
        ),
    ]
