# Generated by Django 5.2.5 on 2025-08-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPreApproved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
