# Generated by Django 5.2.5 on 2025-08-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_users', '0002_staffpreapproved'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpreapproved',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffpreapproved',
            name='invite_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staffpreapproved',
            name='role',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('ADMIN', 'Admin')], default='STAFF', max_length=10),
        ),
        migrations.AddField(
            model_name='staffpreapproved',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
