# Generated by Django 5.2.5 on 2025-09-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_users', '0002_passwordresetotp'),
        ('LMS_users', '0003_staffpreapproved_expires_at_and_more'),
    ]

    operations = [
    ]
